couchbase:
  host: 'couchbase-node1'
  username: 'Administrator'
  password: '123456'
  bucket: 'payment'

mail:
  host: 'mailhog'

postgres:
  dsn: 'host=postgres port=5432 user=postgres password=postgres sslmode=disable TimeZone=UTC connect_timeout=10'