couchbase:
  host: 'localhost'
  username: 'Administrator'
  password: '123456'
  bucket: 'pay.saga'

postgres:
  dsn: 'host=localhost port=5432 user=postgres password=postgres sslmode=disable TimeZone=UTC connect_timeout=10'