version: '3.8'
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - "6379:6379"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"

  couchbase-node1:
    build:
      context: .
    container_name: couchbase-node1
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    environment:
      NODE_TYPE: DEFAULT
      CLUSTER_USERNAME: Administrator
      CLUSTER_PASSWORD: 123456
      CLUSTER_NAME: payment-cluster
      SERVICES: data,index,query,fts
      CLUSTER_RAMSIZE: 500
      BUCKET: payment
      BUCKET_RAMSIZE: 300
      ENABLE_FLUSH: 1
  couchbase-node2:
    build:
      context: .
    container_name: couchbase-node2
    depends_on:
      - couchbase-node1
    environment:
      NODE_TYPE: CHILD
      CLUSTER_USERNAME: Administrator
      CLUSTER_PASSWORD: 123456
      CLUSTER: couchbase-node1
      SERVICES: data,index,query,fts
  couchbase-node3:
    build:
      context: .
    container_name: couchbase-node3
    depends_on:
      - couchbase-node1
      - couchbase-node2
    environment:
      NODE_TYPE: CHILD
      CLUSTER_USERNAME: Administrator
      CLUSTER_PASSWORD: 123456
      CLUSTER: couchbase-node1
      SERVICES: data,index,query,fts
      REBALANCE: 1

  zookeeper:
    hostname: zookeeper
    image: debezium/zookeeper
    ports:
      - "2181:2181"


  kafka:
    image: confluentinc/cp-kafka
    hostname: kafka-broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-ui:
    image: quay.io/cloudhut/kowl:master
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: kafka:9092

  mongo:
    image: mongo
    hostname: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
