spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017
      database: test
    couchbase:
      auto-index: true
  couchbase:
    bootstrap-hosts: couchbase-node1
    bucket:
      name: payment
      password: 123456
      user: Administrator
  kafka:
    bootstrap-servers: kafka-broker-1:9092
    admin:
      properties:
        bootstrap.servers: kafka-broker-1:9092
    consumer:
      bootstrap-servers: kafka-broker-1:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: user-register-group
    producer:
      group-id: payment-service
      bootstrap-servers: kafka-broker-1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  main:
    allow-bean-definition-overriding: true
  application:
    name: payment-service

server:
  port: 9595

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${DISCOVERY_SERVICE:localhost:8761}/eureka/

management:
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: health


kafka:
  payment:
    topic: payment-request
